- name: Generate stage config
  hosts: localhost
  connection: local
  vars:
    git_rev: $PIPE(git rev-parse --short HEAD)
    edxapp_app_dir: /tmp/{{ git_rev }}/stage
    edxapp_user: $PIPE(whoami)
  vars_files:
    - "{{ secure_dir }}/vars/common/common.yml"
    - "{{ secure_dir }}/vars/stage/stage-edx.yml"
  gather_facts: True
  pre_tasks:
    - file:
        path={{ edxapp_app_dir }}
        state=directory
      tags:
        - config
  roles:
    - edxapp

- name: Generate prod config
  hosts: localhost
  connection: local
  vars:
    git_rev: $PIPE(git rev-parse --short HEAD)
    edxapp_app_dir: /tmp/{{ git_rev }}/prod
    edxapp_user: $PIPE(whoami)
  vars_files:
    - "{{ secure_dir }}/vars/common/common.yml"
    - "{{ secure_dir }}/vars/prod/prod-edx.yml"
  gather_facts: True
  pre_tasks:
    - file:
        path={{ edxapp_app_dir }}
        state=directory
      tags:
        - config
  roles:
    - edxapp